SET NOCOUNT ON
SET ANSI_WARNINGS OFF

IF OBJECT_ID ('TEMPDB.DBO.#TEMP') IS NOT NULL  
DROP TABLE #TEMP

SELECT 
	LTRIM(RTRIM(ISNULL(PF.VALOR_PROPRIEDADE,TC.FORNECEDOR))) AS FORNECEDOR,
	DATEPART(MM,TC.DATA) AS MES,
	SUM(TC.QTDE_ENTREGUE) AS QTDE,
	TC.LINHA,
	TC.MARCA

INTO #TEMP

FROM TEMP_COD TC

	LEFT JOIN PROP_FORNECEDORES PF
	ON PF.FORNECEDOR = TC.FORNECEDOR
	AND PF.PROPRIEDADE = '00358'

	LEFT JOIN PROP_PRODUTOS DES
	ON DES.PRODUTO = TC.PRODUTO
	AND DES.PROPRIEDADE = '50019'

WHERE TC.DATA_PROG >= '20200101'
AND TC.DESC_PRODUTO NOT LIKE '%MASCAR%'
AND TC.CANAL <> 'MARKETING'
AND TC.QTDE_ENTREGUE > 0
AND MARCA NOT LIKE 'BYNV'
AND TC.DATA BETWEEN DATEADD(MONTH,-5,GETDATE()) AND GETDATE() 
AND MARCA NOT LIKE '%A.BRAND%' 
AND MARCA NOT LIKE '%F.Y.I%'

GROUP BY TC.FORNECEDOR,
	ISNULL(PF.VALOR_PROPRIEDADE,TC.FORNECEDOR),
	MONTH(TC.DATA),
	TC.MARCA,TC.LINHA




SELECT A.FORNECEDOR,
	A.MES,
	SUM(A.QTDE) AS 'QTDE',
	STUFF((SELECT DISTINCT ','+ RTRIM (LINHA) FROM #TEMP SB
WHERE RTRIM(A.FORNECEDOR) = RTRIM(SB.FORNECEDOR) FOR XML PATH('')),1,1,'') AS 'LINHA',
	A.MARCA,
	STUFF((SELECT DISTINCT ','+ RTRIM (MARCA) FROM #TEMP SB
WHERE RTRIM(A.FORNECEDOR) = RTRIM(SB.FORNECEDOR) FOR XML PATH('')),1,1,'') AS 'MARCA_TRABALHA'



FROM #TEMP A
GROUP BY A.FORNECEDOR,A.MARCA,A.MES
ORDER BY 1
